version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: controfinai-db
    restart: always
    environment:
      POSTGRES_USER: carlosrodrigues
      POSTGRES_PASSWORD: C@r10$IO#*
      POSTGRES_DB: controfinai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: